apiVersion: v1
kind: Service
metadata:
  name: vote
  namespace: voting
spec:
  type: NodePort
  ports:
    - port: 80         # inside cluster
      targetPort: 80   # inside container
      nodePort: 30080  # public port
  selector:
    app: vote
